### ISSUE TITLE
press-level sitemap link leads to unstyled XML

### ISSUE THREAD

**Issue by mdlincoln** [BirkbeckCTP/janeway#1019]
**Describe the bug**
`/sitemap` (which is linked to in the footer of the OLH theme) leads to an unformatted XML document that only seems to display custom-built CMS pages. It does not include links to any other pages. What's the function of this

**Janeway version**
1.3.3.1

**Comment by hachacha** [comment]
Following up on this. 
I am not sure if this is a bug but it seems to be made for janeway instances that have a `URL_CONFIG` of domain instead of path based on the template it would return the articles of that journal. 
However, this is showing up on the front page for our site which is set to `URL_CONFIG = path` so is there any way to hide the sitemap section OLH theme on the press level or other footer elements? 
This can be done through CSS or explicit editing of the template files but is there a best way to do this without diverging from the main codebase?
Other possible solution is to modify the template display and sitemap function to return journals, articles and cms pages.

Thanks

**Comment by mauromsl** [comment]
Hi @hachacha 
It looks like this is how the sitemaps were implemented originally in Janeway, before path/domain modes where implemented (which is why the press only returns CMS urls while the journals return article urls). Other than that, the sitemaps should be working in the same way, regardless of what mode you are running your janeway `URL_CONFIG` on.

That said, it might be a good idea for `path` mode installations to expose a sitemap index file that points to the sitemap of each individual nested site (journal, conference or repository). Would that be of help for your use case?
