### ISSUE TITLE
Use a WYSIWYG editor that allows easy relative links

### ISSUE THREAD

**Issue by mdlincoln** [BirkbeckCTP/janeway#1028]
**Is your feature request related to a problem? Please describe.**
Currently the WYSIWYG editor only creates links that have http:// in front of them, so you need to manually edit the HTML in order to force a relative link.

**Comment by ajrbyers** [comment]
@mdlincoln have attempted to update django-summernote to the latest version but it makes no difference. This has been implemented in summernote but not moved into the django-summernote repo. I've asked when we can expect it. 

On another note @mauromsl and I were discussing using ckeditor instead of the combo of summernote and jqte we currently use so that may supersede this.
