### ISSUE TITLE
Subtitle

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#1502]
**Describe the bug**
This field is not in use

**Janeway version**
Remove this field from submission at the moment,

**Comment by Beethro** [comment]
@ajrbyers 

Hi,

I'd like to ask you to reconsider the removal of the subtitle field from submission, since we do make use of  the field. It may be a "culture" thing, but for us ~25% of the regular articles (meaning non table of contents etc. articles) in our journals carry a subtitle. Since we plan to push the Janeway data to Alma keeping the distincton seems rather important to get a correct MARC 245 field there.

Cheers

**Comment by ajrbyers** [comment]
Hi @Beethro,

We weren't going to delete the field but remove it from submission. Currently on any of the supported themes the field is not used (which is my oversight) so we are discussing how we might resolve that. I think there are two options:

1. Make the field optional so themes that support it can make use of it
2. Update all of the core themes to make use of it

I'll take a look at #2 and see how hard it would be... It may be as simple as adding a new method to `submission.Article` and find/replacing `{{ article.title }}` to use the new method which will output the Title _and_ subtitle fields.

Andy

**Comment by Beethro** [comment]
Hi @ajrbyers ,

Oh, you didn't mean removal from submission_article? Then life ist good :)

All the best.
Oliver

**Comment by ajrbyers** [comment]
> Hi @ajrbyers ,
> 
> Oh, you didn't mean removal from submission_article? Then life ist good :)
> 
> All the best.
> Oliver

Oh no, we just didn't want the field displaying by default as its not in use and confuses people! I'll have a go at option 2 anyway as its the neater solution imo
