### ISSUE TITLE
[Preprints] Site Map

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#1794]
The indexing system would expect the sitemap to be linked from the robots.txt instructions page for the site itself (e.g. https://dev.eartharxiv.org/robots.txt). 

Here are sitemap specs: 
- sitemaps.org protocol
-  include a list of all article-level landing page URLS and fulltext URLs (e.g. PDF/DOC)
- 5MB umcompressed max file size - so if sitemaps are larger than this, feel free to break them into child sitemaps
- updated automatically (ideally daily/weekly)

**Comment by ajrbyers** [comment]
@mwestin-googlescholar

**Comment by tingletech** [comment]
start at the sitemap https://github.com/BirkbeckCTP/janeway/pull/1815

**Comment by tingletech** [comment]
Some notes about the dev site:

- Will a sitemap with article-level URLs be put in place for the live site? Because of the list-based browse structure (with many navigation pages), a sitemap would be necessary to ensure comprehensive indexing. Please let me know if it would be helpful for me to send specs for a sitemap that would work well for Google Scholar indexing.

- I see Dublin Core tags but not the citation_xx metatags that Google Scholar uses for indexing. Would it be possible to add these? 

For example, in the HTML source for https://pub-janeway2-dev.escholarship.org/EA/repository/view/8/ these metatags would look like:

<meta name="citation_title" content="Taking the pulse of salt-detached gravity gliding in the eastern Mediterranean">
- These could be mapped from DC.Title tags, though I noticed that these are sometimes empty on the dev site

<meta name="citation_author" content="Sian Evans">
<meta name="citation_author" content="Christopher Aiden-Lee Jackson">
<meta name="citation_author" content="Davide Oppo">
- These metatags would be listed in the order of author order as listed in the publication. These could be mapped from the DC.Creator tags you have now. 

<meta name="citation_online_date" content="2020-08-05">
- These could be mapped from DC.Date.created tags. 

<meta name="citation_pdf_url" content="https://pub-janeway2-dev.escholarship.org/EA/repository/object/8/download/1427/">
- Question: On the live site, would the PDF be hosted on the same subdomain as the article landing pages? 

<meta name="citation_abstract" lang="en" content="We investigate early-stage salt-detached gliding using a 3D seismic dataset from the Levant Margin in the Eastern Mediterranean, where gravitational instability due to margin uplift has caused north-westward translation of the Messinian salt sheet and its Plio-Pleistocene clastic overburden. Large, NE-trending, base-salt anticlines have allowed the basinward translation to be recorded by the development of supra-salt ramp syncline basins and fluid escape pipes, the latter forming due to the leakage of gas and fluid from the anticline crests.">
 - These could be mapped from the DC.Description tags you have now

More on metatags here: https://scholar.google.com/intl/en/scholar/inclusion.html#indexing

**Comment by ajrbyers** [comment]
I think I made the citation tag changes already.
