### ISSUE TITLE
[Preprints] how can I modify the title and abstract of a pre-existing pre-print on the new system?

### ISSUE THREAD

**Issue by tingletech** [BirkbeckCTP/janeway#1873]
**Is your feature request related to a problem? Please describe.**

https://twitter.com/DrCraigMagee/status/1315551768818987008 

**Describe the solution you'd like**
Some way for authors to edit the metadata (and for the moderators to approve it)

**Describe alternatives you've considered**
The question is do we want to store the history? If yes we may need to fundamentally change the models.
If not, we can store it in VersionQueue and then simply over-write the title and abstract.

**Additional context**

I started to look at the VersionQueue solution 
https://gist.github.com/tingletech/c8206ff653f648509dc89c5917c54980 

the text in the help box made it sound like it would not trigger a new version " If this is a completely new version of this manuscript, upload it and a new version will be generated and the older version retained for posterity."  If every metadata edit triggers a new version, that seems confusing.

Andy suggested: "Could change it to allow a quick replace with correction." but I could not see an obvious way of how to do that.

**Comment by justingonder** [comment]
@tingletech @ajrbyers 
In testing, the following issues were discovered with this patch:
- From the [Repository Manager dashboard](https://dev.eartharxiv.org/repository/manager/), clicking on the title of an Unpublished Preprint that has pending revisions results in a 404 (e.g. MS 1735 "Revision Test")
- From the [Versions Moderation queue](https://dev.eartharxiv.org/repository/manager/versions/), clicking on View Detail for an item with a pending **Metadata Correction** has no effect. (Clicking View Detail for an item with a pending **Text Correction** results in a modal appearing that details the changes, which is what is expected when clicking the same for a Metadata Correction.) Moderators can therefore not see what changes have been made before approving those changes.
- In the Version Moderation queue, the ID column in the table contains unexpected values that do not relate to the manuscript's actual ID. This would make it difficult to understand which entries in the table relate to the same MS, especially in cases when multiple revisions for a single entry are present in the table.
- As an author, there is no clear indication that a Metadata Update has been successfully entered. Clicking the Submit Update button simply returns the user to the Preprint #---- Summary page. A notification that the update has been submitted would help here. From that page, an author can click through to immediately submit another Metadata Update, and the previously submitted update is not reflected (i.e. the _original_ title and abstract are still displayed). This may cause a user to submit unnecessary duplicate changes since they are not getting UI feedback that their changes are now saved and pending.
<img width="1378" alt="2020-12-09_12-44-49" src="https://user-images.githubusercontent.com/29953714/101675401-5dfa1600-3a1f-11eb-8c3f-ae9d9cd482c8.png">

**Comment by ajrbyers** [comment]
@tingletech @justingonder does anything of this remain open that isn't in another issue?

**Comment by tingletech** [comment]
@ajrbyers I think this all done; but didn't auto-close b/c the fix is not merged to master yet?
