### ISSUE TITLE
Several settings not available from manager

### ISSUE THREAD

**Issue by hachacha** [BirkbeckCTP/janeway#1916]
**Describe the bug**
some settings pages are not loading.
```
DoesNotExist at /manager/settings/submission/
Setting matching query does not exist.
```

**Janeway version**
Tried both 2716656f41a2e116182676ddb42cebf31baf07
and 509b344b26075b2480872489903a4d3cd3282d8a

**To Reproduce**
Go to http://site/journal/manager
click on review settings, or submission settings, or article display settings and you will get

```

Request Method: | GET
-- | --
http://localhost:8000/ETHOS/manager/settings/article/
1.11.29
DoesNotExist
Setting matching query does not exist.
```

**Expected behavior**
we get to see the setting pages like one does for crossref settings or journal settings.

**Additional context**
I see you updated how the email template settings are displayed in the url so maybe this is related? Do they exist, but the url has changed for a different lookup?

**Comment by mauromsl** [comment]
Hi @hachacha 
The change we made was to unify the logic of the different settings pages (the email settings had their own logic) but wouldn't expect that to affect the other settings pages. We have, however added a few new settings on the latest release. Have you ran `python3 src/manage.py load_default_settings` since the upgrade?

**Comment by hachacha** [comment]
Thank you I had forgotten to run that. 
I will make a habit of running the full update.sh script
