### ISSUE TITLE
Nothing in "Section" dropdown list in "Article Info" Page 

### ISSUE THREAD

**Issue by StVicious** [BirkbeckCTP/janeway#221]
Hi, I was trying to upload an article. When I get to the "Article Info" page, there was nothing to select in the "Section" drop down. The system keep asking me to "Select an item in the list", and will not allow me to move on to the next step (Author information. I tried in Safari and Chrome and got the same issue. Appreciate your help!

**Comment by StVicious** [comment]
Attaching screenshot:

![section_list_empty](https://user-images.githubusercontent.com/4967666/32034704-0ace1168-b9c9-11e7-8ce0-0750aba5b594.png)

**Comment by ajrbyers** [comment]
This is because you have not created any sections. this can be done from /manager/sections/ I will make a note for this to be added to the next steps page of the install page.

This type of question would be much better suited to our Slack channel, if you'd like an invite drop me an email on a.byers@bbk.ac.uk

**Comment by ajrbyers** [comment]
@StVicious do you think it would be worthwhile for the install process to create a set of basic sections? Simple ones like:

- Article
- Review

**Comment by StVicious** [comment]
I think that if there was some sort of help text next to the dropdown, telling the user that they need to create sections, and perhaps providing a link to where they can create the sections, that would make the process more intuitive.

**Comment by ajrbyers** [comment]
fc45dea1318f8178ae3cf46b7cf985ab86388e3d
