### ISSUE TITLE
[XSLT] Title tags not being rendered in appendix blocks

### ISSUE THREAD

**Issue by mauromsl** [BirkbeckCTP/janeway#2277]
**Describe the bug**
Similar to another issue we previously resolved in reference blocks, appendix elements <app> are ignoring <title> child objects.

**Janeway version**
v1.3.9

**Additional context**
Noted on this article https://poetry.openlibhums.org/article/id/3401/
The title "appendix" had to be moved out of the appendix itself in order for it to be rendered.

**Comment by pgoussy** [comment]
@mauromsl @ajrbyers We're encountering this again with the current batch of TIA articles. We can work around it relatively easily (i.e., by copy-pasting the <title> text into the <label> field instead) but it would be nice if we could just use <label> and <title> tags as intended.

One intriguing wrinkle is that this issue does _not_ seem to occur within <sec> tags that are contained within <app> tags. See the screenshot: the Appendix A <title> does not display, but the Section I <title> displays just fine. Perhaps the problem isn't specific to <app>, but simply to <title> tags that aren't contained within a <sec>? Just theorizing.

![2021-10-11_15-30-46](https://user-images.githubusercontent.com/36245100/136845913-57c75ad5-5aad-4f9e-ae6e-7c4a0940be09.png)
.

**Comment by pgoussy** [comment]
@mauromsl @ajrbyers Bumping this up again because it appears that the scenario I described in my previous comment has somehow been inverted: now the `<title>` immediately after `<app>` _is_ rendering as expected, but each `<title>` contained within a `<sec>` within the `<app>` is _not_ displaying in the HTML (they appear to be turning into empty `<h3>`s instead).

https://journals.publishing.umich.edu/ptpbio/plugins/typesetting/preview_galley/article/2102/galley/965/#heading18

![2022-07-06_14-56-27](https://user-images.githubusercontent.com/36245100/177622979-3cc032a5-5ea5-40a4-8a93-91df26447ec8.png)

**Comment by pgoussy** [comment]
I just did some trial and error to see if the same applies to `<label>` and the results were intriguing:

- If `<label>` is contained directly in `<app>` it displays in the same `<h2>` as the `<title>` (per #2911 , if there's no `<title>` then the `<label>` won't display at all)
- If  `<label>` appears alongside `<title>` in a `<sec>` within `<app>` then the `<label>` _does_ display in the HTML--but the `<title>` still does not.
- If  `<label>` appears in a `<sec>` within `<app>` _without_ being accompanied by `<title>`, it doesn't display at all (consistent with #2911 ); it doesn't even generate an empty `<h3>` like the `<title>` on its own did.
![2022-07-06_15-21-01](https://user-images.githubusercontent.com/36245100/177626771-754c6133-2dd5-4c09-af76-0770bfe7c6dc.png)

**Comment by pgoussy** [comment]
Bumping this up. We've got workarounds, but they're awkward, and it would be nice to not have to worry about this every time we work on an appendix!
