### ISSUE TITLE
Bleach

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#2282]
**Is your feature request related to a problem? Please describe.**
Users _often_ insert bad HTML or code from MS Word when pasting into certain fields.

**Describe the solution you'd like**
Implement a process to strip these bad tags from title and abstract fields.

**Comment by AmeliePlaysKath** [comment]
had some further problems with stripping html from Labphon's site this morning, where leading was too tight and couldn't be stripped. Finally figured it out by pasting html version to https://www.browserling.com/tools/html-strip 
In case it helps, from OLHJ's perspective it would be useful for the cleaner with an HTML erasing option that can retain paragraphs, hyperlinks, italicisation and bold, but remove everything else. Also, an 'undo' option so that editors can feel more confident with experimenting. Hope this helps :)

**Comment by joemull** [comment]
Note on implementation: Andy was planning to use this: https://django-bleach.readthedocs.io/en/latest/
