### ISSUE TITLE
OLH Theme: Is Peer Reviewed

### ISSUE THREAD

**Issue by ajrbyers** [BirkbeckCTP/janeway#2320]
**Describe the bug**
When an article is not peer reviewed, either don't display the block or display text to that effect.

**Additional Details**
This issue has been reopened since many users have complained about the insertion of the text by default. Some of the concerns raised were: 
    (a) journals that don't do "peer review" in the strictest traditional sense, but do perform a thorough editorial review, and don't want the implied negative value judgment of "not peer reviewed" on their articles; 
   (b) journals that do use traditional peer review, but don't want to explicitly highlight content that isn't, like front matter, book reviews, etc.

If re-introduced, the text should be configurable with a three-way toggle
 1. do not display peer review status at all
 2. display peer review status only when articles have been peer reviewed
 3. display peer review status in all cases

The setting needs to be configurable at the section level

**Janeway version**
1.3.10

**Comment by mauromsl** [comment]
** Additional Details **
This issue has been reopened since many users have complained about the insertion of the text by default. Some of the concerns raised were: 
    (a) journals that don't do "peer review" in the strictest traditional sense, but do perform a thorough editorial review, and don't want the implied negative value judgment of "not peer reviewed" on their articles; 
   (b) journals that do use traditional peer review, but don't want to explicitly highlight content that isn't, like front matter, book reviews, etc.

If re-introduced, the text should be configurable with a three-way toggle
 1. do not display peer review status at all
 2. display peer review status only when articles have been peer reviewed
 3. display peer review status in all cases

The setting needs to be configurable at the section level

**Comment by mauromsl** [comment]
done in [20d0057](https://github.com/BirkbeckCTP/janeway/commit/20d0057f446f7acf3eb73f16d9a5b2a520e6cb2e)
