### ISSUE TITLE
Allow email templates to be fully editable / customizable 

### ISSUE THREAD

**Issue by lstachew** [BirkbeckCTP/janeway#2380]
**Is your feature request related to a problem? Please describe.**
Many functions in Janeway trigger email. Some of the emails are automatic and behind-the-scenes and some load in editable windows before sending. The editable email that populates when an article is declined in Janeway doesn't allow the user to add attachments or to modify the subject line. In fact, how the system handles these editable emails across the platform seems pretty random.

**Describe the solution you'd like**
It would be nice to be able to fully edit any email the system allows the user to interact with, including the subject line, the main text, and add attachments.
It would also be nice to allow editors to develop their own email templates for journal-specific things. For example, the system's email template for requesting revisions is the same whether you're requesting pre-review revisions, minor revisions, or major revisions.

**Comment by ajrbyers** [comment]
Hi @lstachew,

Can you clarify what you mean by random? 

What sort of attachment would you need to add at this point, considering the revision process gives the author access to their MS and Review files, I can’t think of any. 

Subjects are customisable but not editable, this is not an accident. 

Allowing editors to curate their own templates is an interesting idea, though they would need to be aware of the context. Ie they might load a template that uses variables not present for a given context.

**Comment by mp6h** [comment]
@ajrbyers By random, I mean that the ways system emails are presented inside of Janeway varies across the site. Some allow you to add attachments (e.g. accepting a manuscript) some don't (e.g. declining a manuscript). Some allow you to edit the subject (e.g. sending review reminders), some don't (e.g. declining a manuscript). 

There are many reasons why an editor might want to attach a separate file to an out-going email. An example: When sharing reviewers' feedback with authors, Janeway shares the reviewers' decisions. This is not something we do at our journal since reviewers' recommendations don't always align with their feedback and they can be drastically different from one reviewer to the next. So, we manually copy the reviewers' feedback into one doc and attach it to the message with the editor's decision. Regardless, it seems useful enough to implement across the site.

**Comment by ajrbyers** [comment]
> @ajrbyers By random, I mean that the ways system emails are presented inside of Janeway varies across the site. Some allow you to add attachments (e.g. accepting a manuscript) some don't (e.g. declining a manuscript). Some allow you to edit the subject (e.g. sending review reminders), some don't (e.g. declining a manuscript).
> 
> There are many reasons why an editor might want to attach a separate file to an out-going email. An example: When sharing reviewers' feedback with authors, Janeway shares the reviewers' decisions. This is not something we do at our journal since reviewers' recommendations don't always align with their feedback and they can be drastically different from one reviewer to the next. So, we manually copy the reviewers' feedback into one doc and attach it to the message with the editor's decision. Regardless, it seems useful enough to implement across the site.

Sure - I suspect if anything that update that added this was probably just missed from that page. 

So there are three main issues:

- Allow editing of all subjects as with emails
- Ensure all email pages have attachment ability
- A separate issue needs to be added to request the ability to hide the reviewer decision?

**Comment by mp6h** [comment]
Yep, those are the three issue. The last one would be a big help.

**Comment by joemull** [comment]
We are going to split out the email attachment part of this issue and handle it in #3027.

**Comment by mauromsl** [comment]
We added support for all these fields in 1.5.1: #3121
