### ISSUE TITLE
JATS footnote comment rendering issues

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#2587]
When a footnote contains a JATS `<comment>` it is rendered as HTML `<small>` with a preceding `<br>` but should not be. Reported by @pgoussy.

https://jats.nlm.nih.gov/publishing/tag-library/1.3/element/comment.html

https://journals.publishing.umich.edu/tia/plugins/typesetting/preview_galley/article/959/galley/259/
![Screenshot from 2021-11-04 13-13-46](https://user-images.githubusercontent.com/47217308/140387402-2e0381eb-e0a0-435e-9671-187780e2de57.png)
![Screenshot from 2021-11-04 13-23-07](https://user-images.githubusercontent.com/47217308/140388714-3fa6e07a-6fda-491c-9eb4-7eee33855873.png)

**Comment by pgoussy** [comment]
Just an FYI because I noticed that we didn't mention it in the original ticket: the comment tag also prevents URLs from rendering in the HTML. It'll say something like "Retrieved from ." with the URL simply not showing up in Janeway at all.

I'm not sure if @ajrbyers 's commit re: "ext-link in citation comments" is related to this, but I wanted to get it on the record.

![2021-12-08_13-45-04](https://user-images.githubusercontent.com/36245100/145265905-dd476f8c-0561-40f9-9701-4fcbc7629335.png)

**Comment by ajrbyers** [comment]
Hey @pgoussy yes that commit fixes this.
