### ISSUE TITLE
Asterisk in JATS label rendered as bullet point

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#2588]
When an asterisk is used as a the label for a footnote on a table, it is rendered as a bullet point. 

https://journals.publishing.umich.edu/tia/plugins/typesetting/preview_galley/article/959/galley/259/#tab2
![Screenshot from 2021-11-04 14-00-27](https://user-images.githubusercontent.com/47217308/140394508-d520a997-fb60-4285-b8c3-9272a62df90d.png)
![Screenshot from 2021-11-04 13-59-58](https://user-images.githubusercontent.com/47217308/140394513-d30cacdd-8f9b-42f0-9ef7-0186fc399c66.png)

**Comment by pgoussy** [comment]
Update: as a workaround, I asked the XML vendor to remove the `<label>` tags. In doing so, I learned that apparently it's not the `<label>*</label>` causing the bullet point to appear, because now I'm seeing a bullet point AND an asterisk. The bullet point must be somehow inherent to the table footnote tagging.
![2021-11-10_16-34-11](https://user-images.githubusercontent.com/36245100/141196941-bcd25f91-695a-46b0-b522-0c3b504e6461.png)

**Comment by joemull** [comment]
Getting reports that list-type attributes are all still rendering with Arabic numerals (even with, for example, list-type="alpha-lower"). Is this resolved?

**Comment by pgoussy** [comment]
FWIW @ajrbyers said he'd added support for all of the list-types in a response to a freshdesk ticket (https://janeway.freshdesk.com/support/tickets/4263) but maybe it never got added to the release candidate?

**Comment by joemull** [comment]
> FWIW @ajrbyers said he'd added support for all of the list-types in a response to a freshdesk ticket (https://janeway.freshdesk.com/support/tickets/4263) but maybe it never got added to the release candidate?

@pgoussy I commented on the wrong issue--we've got a new issue for this here: https://github.com/BirkbeckCTP/janeway/issues/2744
