### ISSUE TITLE
Enlarge pictures in the frontend

### ISSUE THREAD

**Issue by MatthiasULB** [BirkbeckCTP/janeway#3101]
**Is your feature request related to a problem? Please describe.**
When clicking on pictures in the HTML, they are not enlarged but downloaded.

**Describe the solution you'd like**
Enlarge pics in the frontend, maybe with a lightbox or something alike? Download should still be an option.

**Comment by pgoussy** [comment]
Bumping up this request, as one of Michigan's image-heavy journals has requested the same functionality.

**Comment by joemull** [comment]
A couple of thoughts on this:
- My guess is most users would expect enlarged images before downloaded images, on a simple click, so I am leaning toward a blanket implementation rather than a setting, though I could be wrong
- If we made enlarge-to-click the default, there would need to be an obvious download button
- It might get tricky to implement this in different themes, which (rightly) have different JavaScript utilities, while preserving the look and feel of that theme
- What if we implemented enlarge-to-click for one theme, to start, and encourage image-heavy journals to use it? What themes are these journals using, @MatthiasULB and @pgoussy?

**Comment by MatthiasULB** [comment]
Hi @joemull, thanks for looking at this! 

>What themes are these journals using, @MatthiasULB and @pgoussy?

[JCLS](https://jcls.io/) is using the OLH theme.

I agree with you about making enlarge-to-click the default. I don't have statistics on usage behavior at hand, but I also think most people expect the image to be enlarged. I would right click and "save image as..." if want to download it. But a included download button would still be a cool thing.

**Comment by ajrbyers** [comment]
Our base XSL already inserts a download link in the image caption space. 

I think you’re right about this being a blanket implementation across all themes. We’ve talked previously about using lightbox to implement this so it’s consistent across themes.

**Comment by pgoussy** [comment]
Ars Orientalis is the MPS journal that recently asked about this, and they haven't fully settled on a theme yet because they want to wait and see what the actual article content looks like in OLH vs Material (because they won't really be using aboutware pages on Janeway)

**Comment by joemull** [comment]
Roger, thanks all.

I just realized I wrote "enlarge-to-click" 😆  I meant "click-to-enlarge"!

**Comment by MatthiasULB** [comment]
Lol and I just took that on in my answer 😂

**Comment by pgoussy** [comment]
Is it safe to assume that this feature isn't happening in the _near_ future? Ars Orientalis is asking about changing the display for their figures prior to publication.

**Comment by joemull** [comment]
@pgoussy sorry for the slow reply. Yes, I estimate it will be at least a month before we would be able to roll this out as part of the next release, even though I see Andy has self-assigned this issue today.
