### ISSUE TITLE
Logs should be able to be filtered by source, type, actor

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#3224]
**Is your feature request related to a problem? Please describe.**
As a system administrator, I would like to regularly assess our logs to use in determining what support repository managers / editors are providing in Janeway and how. 

**Describe the solution you'd like**
I would like to be able to filter logs by the following: 

1. Source (e.g. repository ID, journal ID, "system") 
2. Person performing the action (user identifier)
3. Type of action 
4. Date of action

**Comment by joemull** [comment]
We are going to handle items 2-4 in #3256, a much more comprehensive cleanup of the admin views.

However, there is no good way to handle item 1 (journal / repository) without adding a field to the LogEntry model and populating that field when creating logs. So, this issue is really about adding a ForeignKey field to LogEntry, or rather one field for journal and one for repository, and then making sure to populate them everywhere when creating entries.

**Comment by joemull** [comment]
Another option is to use a custom list filter: https://docs.djangoproject.com/en/1.11/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_filter

If we write a custom list filter for generic foreign keys, we could use it in quite a few places in the admin views.

So, I'll try to add filtering by source system along with #3256.
