### ISSUE TITLE
Null data on ORCID record results in orcid.py errors (user doesn't see)

### ISSUE THREAD

**Issue by alainna** [BirkbeckCTP/janeway#3622]
**Describe the bug**
If the ORCID record data being checked in https://github.com/BirkbeckCTP/janeway/blob/master/src/utils/orcid.py#L78 is null or not visible to the API client making the call, then an error is thrown. 

**Janeway version**
1.5.0 

**To Reproduce**
1. In an ORCID record that you control and which is not connected to Janeway, set all name and email fields to trusted parties (read-limited) or only me (private) (example: https://pub.orcid.org/v3.0/0009-0007-4600-3310 ) 
2. Sign in or register with Janeway using that ORCID record 
3. Log in/register as expected
4. View error message 
    > TypeError: 'NoneType' object is not subscriptable 
    > File "utils/orcid.py", line 86, in get_orcid_record_details
    > details["last_name"] = user_record["name"]["family-name"]["value"]

**Expected behavior**
Janeway would ignore, not throw up error

**Comment by mauromsl** [comment]
@alainna #3758 fixes this specific issue, however the user with your provided ORCID would still be unable to use our 'log in with ORCID' feature as they don't have a public email address that we can correlate with a Janeway account. So that will still be an issue until we have a proper ORCID authentication flow.
