### ISSUE TITLE
Control user button issue

### ISSUE THREAD

**Issue by S-Haime** [BirkbeckCTP/janeway#3785]
Reported by Longleaf (ticket #7466)

"When I go into the Manager role and to the "Enrolled Users" area of any journal, the "Control User" button in the first row of the list of users appears to be functioning as the "Add Users to Role" button. When I clicked "Control User" in the row for a user (see screenshot below), I got the error message "No users selected," which is what happens if I click "Add Users to Role" without selecting a box. 

The "Control User" buttons for all other rows work as expected. It's just happening in the first row. Could you please look into this apparent bug?
![image](https://github.com/BirkbeckCTP/janeway/assets/148049561/a26d5f00-44db-49a9-8bfe-378dd3061ee1)

**Comment by StephDriver** [comment]
When testing, this appears to be an issue with trying to control oneself, rather than it being the first line - would the original reporter have also been the first user on that list?

A user cannot control themself (!) - but the error code that no user is selected is unhelpful for this situation.

**Comment by S-Haime** [comment]
Hi @StephDriver - the user was not trying to control themselves and they were not the first users on the list (I checked).

**Comment by StephDriver** [comment]
Investigation:  
problem is related to lowest user.pk rather than position in table.  When tested with two users (pk 1, 2) the 1 showed this bug whether in top line of user table or bottom.  2 didn't show the bug in either position.  pk appears to be correct on each line of table.

next step - 
test with multiple users were lowest user.pk is not 1 as to whether this is specific to pk=1 or whether it is about the lowest pk.

**Comment by S-Haime** [comment]
So this still seems to be an issue... See [FD](https://janeway.freshdesk.com/a/tickets/8232)

**Comment by ajrbyers** [comment]
I don’t think it’s been deployed to UNC yet.

**Comment by S-Haime** [comment]
I shall inform Stacy!
