### ISSUE TITLE
When I register a theme as an app it takes over

### ISSUE THREAD

**Issue by joemull** [BirkbeckCTP/janeway#3793]
**Describe the bug**
When I register a press-level them as an app (like https://github.com/BirkbeckCTP/hourglass) the base template is used even on journals with a different theme set in the manager. Changing `INSTALLATION_BASE_THEME` in `settings.py` does not change this behavior.

**Janeway version**
1.5.0

**Comment by mauromsl** [comment]
I think this is a configuration issue on the loaders, rather than a problem with adding your theme as an app.

See the order of the loaders on `settings.py` our custom `utils.template_override_middleware` loader should come before the `django.template.loaders.app_directories.Loader` to ensure the theming takes precedence over the default django behaviour

**Comment by joemull** [comment]
For future reference, this was an issue caused by the order of the template loaders combined with loader caching. Long story short, we should not use template loader caching with our theme configuration.
