### ISSUE TITLE
MathOverflow

### ISSUE THREAD

**Issue by rossmounce** [BirkbeckCTP/janeway#380]
One of the lines of maths overflows the box and gets obscured by the table of contents box.
The last bit is ( s + c ) with the + c ) obscured
https://doi.org/10.16995/orbit.486

![mathoverflow](https://user-images.githubusercontent.com/824120/36841929-ebe94772-1d41-11e8-83bf-20dd11b992d3.JPG)

Win10 Enterprise, Google Chrome Version 64.0.3282.186 (Official Build) (64-bit)

**Comment by ajrbyers** [comment]
Thanks for the report @rossmounce, missed these because they don't show on my main monitor. The Material theme has been updated with:

`.disp-forumula { overflow-x: auto }`

Which while a bit ugly will make the equations readable.

![screenshot from 2018-03-01 11 46 40](https://user-images.githubusercontent.com/8321378/36843400-be509dc4-1d46-11e8-8d81-748c8b95660a.png)

**Comment by MartinPaulEve** [comment]
(And just to add, further, that this is a problem with MathJax and wrapping/responsive design. The overflow scroll solution was the best we can do for now until they update their linewrapping code.)
