### ISSUE TITLE
Author login landing page

### ISSUE THREAD

**Issue by S-Haime** [BirkbeckCTP/janeway#4026]
"The first thing is that when you log in as an author, you go directly to the dashboard. We would prefer that when you log in, you simply log in to the homepage. Where you can then go to your dashboard (or submit) in the top right corner."

Note: we may wish to speak to uGent again and do some UX work around this to see how other users / authors experience this and what the preferred page would be.

I have added @Astronaut-resting to this ticket so she is aware.

**Additional context**
Requested through FD by uGent #8004. May need UX input.

**Comment by joemull** [comment]
We discussed this in refinement, and we felt that going to the dashboard is a typical expectation when you log in to a system. In the past, users were actually taken back to the homepage after logging in, but we changed it because people asked us to.

We have opted to close this for now, but we can return to in a UX survey if desired.
